// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBneVo7ibF-tpeUJnmgp8yFQw8GuNrS4',
    appId: '1:639811708002:web:e62194bff64c58dc945d3b',
    messagingSenderId: '639811708002',
    projectId: 'moger-pro',
    authDomain: 'moger-pro.firebaseapp.com',
    storageBucket: 'moger-pro.appspot.com',
    measurementId: 'G-LVS8L9GHR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5Y8VuXB4Y57nFiIZA_Pqy9-HiUOF8aU',
    appId: '1:639811708002:android:28489ee2b94c406d945d3b',
    messagingSenderId: '639811708002',
    projectId: 'moger-pro',
    storageBucket: 'moger-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMfjE4Aa38X_44jWeKxu_SOASPySCvmOk',
    appId: '1:639811708002:ios:529785047912323e945d3b',
    messagingSenderId: '639811708002',
    projectId: 'moger-pro',
    storageBucket: 'moger-pro.appspot.com',
    iosBundleId: 'com.example.mogerWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMfjE4Aa38X_44jWeKxu_SOASPySCvmOk',
    appId: '1:639811708002:ios:de3231ebc07a086c945d3b',
    messagingSenderId: '639811708002',
    projectId: 'moger-pro',
    storageBucket: 'moger-pro.appspot.com',
    iosBundleId: 'com.example.mogerWeb.RunnerTests',
  );
}
